### ISSUE TITLE
Tutorial link is broken

### ISSUE THREAD

**Issue by sijie** [apache/distributedlog#137]
The `tutorial` link in https://distributedlog.incubator.apache.org/docs/latest/tutorials/messaging-4.html is broken. It seems to be related to package rename.

**Comment by zhaijack** [comment]
Would like to help on this.

**Comment by zhaijack** [comment]
https://github.com/apache/distributedlog/pull/140 is for this fix

**Comment by sijie** [comment]
@zhaijack thank you for your contributions. #140 is merged.
