### ISSUE TITLE
Other graduation change items

### ISSUE THREAD

**Issue by zhaijack** [apache/distributedlog#141]
- remove the "-incubating" from the code base.

- change website link from http://distributedlog.incubator.apache.org into https://bookkeeper.apache.org/distributedlog

- change repo from https://github.com/apache/incubator-distributedlog into https://github.com/apache/distributedlog

- git from https://git-wip-us.apache.org/repos/asf/incubator-distributedlog.git into https://gitbox.apache.org/repos/asf/distributedlog.git

- remove website foot, whch contains incubate infos in websiteindex.md

- remove Disclaimer file, which contains this info:
```
Apache DistributedLog is an effort undergoing incubation at The Apache Software Foundation (ASF),
sponsored by the Apache Incubator PMC. Incubation is required of all newly accepted projects until
a further review indicates that the infrastructure, communications, and decision making process have
stabilized in a manner consistent with other successful ASF projects. While incubation status is not
necessarily a reflection of the completeness or stability of the code, it does indicate that the
project has yet to be fully endorsed by the ASF.
```

**Comment by zhaijack** [comment]
https://github.com/apache/distributedlog/pull/143 is for the fix

**Comment by sijie** [comment]
#143 is merged.
