### ISSUE TITLE
Introduce backward compatibility testing

### ISSUE THREAD

**Issue by sijie** [apache/distributedlog#160]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

We need a test mechanism to verify backward compatibilities.

- e.g. 0.4 and 0.5 client can talk to twitter bookie
- 0.4 DL can talk to 4.5 bookies.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*blocker* - we need this to make sure 0.5 release is backward compatible with twitter bookkeeper.

3. Provide any additional detail on your proposed use case for this feature.

we might consider building various docker image and use those docker image for testing.

**Comment by leighst** [comment]
its not clear these are intended to be automated - are they automated or do they require manual run?

**Comment by sijie** [comment]
@leighst It will be automated in CI. I will add it to the CI job to let them run for every pull request, once the changes are in.
