### ISSUE TITLE
Enable checkstyle for all modules

### ISSUE THREAD

**Issue by sijie** [apache/distributedlog#165]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

checkstyle is disabled in some modules. it would be good to enable checkstyle on all modules, to enforce code styles.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*nice-to-have*

3. Provide any additional detail on your proposed use case for this feature.

we can follow apache/bookkeeper#230 to divide this into multiple small tasks

**Comment by ArvinDevel** [comment]
checkstyle has been applied to several modules, including distributedlog-proxy-server,distributedlog-proxy-client, distributedlog-protocol,distributedlog-core-twitter,distributedlog-common and distributedlog-benchmark.
So add checkstyle to below modules:
- [ ] distributedlog-core

- [ ] distributedlog-proxy-protocol

- [ ] distributedlog-tutorials

- [ ] tests
