### ISSUE TITLE
Missing dependency: bookkeeper-server 4.3.7-TWTTR-OSS

### ISSUE THREAD

**Issue by benalexau** [apache/distributedlog#243]
- What did you do?

I added http://maven.twttr.com/ to the local Nexus server and then attempted to build from source 832fb4eac37439ecbb1eb910ba3f7b8a502ba40f using `mvn install -DskipTests`.

- What did you expect to see?

Compiled JARs.

- What did you see instead?

Failed with:

```[ERROR] Failed to execute goal on project backward-compat-test-0.4: Could not resolve dependencies for project org.apache.distributedlog.tests:backward-compat-test-0.4:jar:0.6.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.bookkeeper:bookkeeper-server:jar:4.3.7-TWTTR-OSS, org.apache.bookkeeper.stats:bookkeeper-stats-api:jar:4.3.7-TWTTR-OSS: Failure to find org.apache.bookkeeper:bookkeeper-server:jar:4.3.7-TWTTR-OSS```

Workaround is to edit `test/pom.xml` and disable modules `jmh-0.4` and `backward-compat-0.4`.

The [Admin Guide BookKeeper page](http://bookkeeper.apache.org/distributedlog/docs/latest/admin_guide/bookkeeper.html) states:

> The version of BookKeeper that DistributedLog depends on is not the official opensource version. It is twitter's production version 4.3.4-TWTTR, which is available in https://github.com/twitter/bookkeeper.

However the error message shows `4.3.7-TWTTR-OSS` is being used. Also `mvn dependency:tree` shows `4.7.0-SNAPSHOT` is the typical version. 

Is `4.3.7-TWTTR-OSS` available in a public Maven repository somewhere (or could a Twitter person perhaps add it to http://maven.twttr.com/)?

**Comment by sijie** [comment]
@benalexau we have moved to the official bookkeeper release. I think the admin guide page is out of date. I don't think it should use 4.3.7-TWTTR-OSS. Let me check why you will get this error.

**Comment by sijie** [comment]
Ah I see what is the problem here: backward-compat-0.4 is using distributedlog `0.4-incubating` for backward compat tests. distributedlog `0.4-incubating` is using `4.3.7-TWTTR-OSS`, which this version in twitter's github repo. (see the pom file in 0.4-incubating: https://github.com/apache/distributedlog/blob/release-0.4.0-incubating/pom.xml#L256) you need to add this to your local nexus server, i guess.

**Comment by benalexau** [comment]
Thanks @sijie. I added `https://raw.githubusercontent.com/twitter/bookkeeper/mvn-repo/4.3.7-TWTTR-OSS/` as a repository to the local Nexus and it resolved fine.

**Comment by sijie** [comment]
Glad to hear it works!
